### ISSUE TITLE
log.pinterest.com 502 (BAD_GATEWAY)

### ISSUE THREAD

**Issue by jchatard** [pinterest/widgets#10]
For a few weeks now (1 or 2 I don't know) I have this error upon page load using `pinit.js`.

Either using a local copy or the one hosted by pinterest.com, no difference. My only option so far would to remove Pinterest from my website, but that sucks right?

`Failed to load resource: http://log.pinterest.com/?via=http%3A%2F%2Fwww.breek.fr%2Fprojets&guid=FKXeezB5UFcp&type=pidget&callback=PIN_1381932797699.f.callback[0] the server responded with a status of 502 (BAD_GATEWAY)`

**Comment by jh20001** [comment]
I know this is old, but if anyone sees this...consider that you might be using an ad-blocker or something similar on your browser or network. Let it be a plugin in your browser or something like Pi-Hole. Just a thought, as this would cause something like this. 

I know because I experienced the same thing now, six years later. I disabled pi-hole and reloaded the page. All good. 

An FYI for anyone landing here ;)

**Comment by rolero** [comment]
We have the same problem at a customer of us at the moment. Suddenly it gives a 400 error.

This is the webpage: https://www.allbusinesstemplates.com/template/Z8BUG/authorization-letter-to-claim-money/

We only load the following as JS: 
`<script async defer src="//assets.pinterest.com/js/pinit.js"></script>`

This script creates a request to:
https://log.pinterest.com/?type=pidget&guid=hgjLzoFNKnQm&tv=2019040401&event=init&sub=nl&button_count=1&follow_count=0&pin_count=0&profile_count=0&board_count=0&section_count=0&lang=nl&nvl=nl&via=https%3A%2F%2Fwww.allbusinesstemplates.com%2Ftemplate%2FZ8BUG%2Fauthorization-letter-to-claim-money%2F&callback=PIN_1579779360139.f.callback[0]

If we remove the parameter type from the url we get a 200. Problem is that we can't contol this

Please re-open and advice

**Comment by karthickbadrick** [comment]
hi

**Comment by karthickbadrick** [comment]
![image](https://user-images.githubusercontent.com/34476082/159845351-3a9328c6-2856-459b-8763-dd74134c9284.png)
now we are facing the same issue, give me better solution
