### ISSUE TITLE
Count API always returns JSONP even when requested not to

### ISSUE THREAD

**Issue by kristoferbaxter** [pinterest/widgets#101]
AMP Pinterest components depend on the `count.json` api under the `v1` namespace, but cannot execute jsonp for security reasons.  Previously the `v1` api returned json when the `return_jsonp=false` url parameter was included in the request.

Something appears to have changed, and now the response is always jsonp.

https://widgets.pinterest.com/v1/urls/count.json?return_jsonp=false&url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fkentbrew%2F6851755809%2F&__amp_source_origin=http%3A%2F%2Flocalhost%3A8000

**Comment by kristoferbaxter** [comment]
See related issue: https://github.com/ampproject/amphtml/issues/32333

**Comment by kentbrew** [comment]
Checking on this now.

**Comment by kentbrew** [comment]
Fixed, sorry this took so long.

**Comment by kristoferbaxter** [comment]
No worries, thanks for addressing!
