### ISSUE TITLE
Dynamic embedding 

### ISSUE THREAD

**Issue by Antonio-Laguna** [pinterest/widgets#13]
Hi there,

It seems that embedding is fine but if you want to do dynamic embedding, you're out of look. I spent a lot of time trying to dig in your minified files to see how could I do that... 

I loose the trace at `doBuild` since I don't see that function being defined anywhere. That function seems to encapsulate the `build` function in the `PIN_X` global object, that's quite useful, given the fact that X is Date dependent so you can't invoke that function from your code.

Do you have a magic way to do this?

**Comment by BarbaraMae** [comment]
@kentbrew I'm trying to use this feature to load a new set of embedded boards using an ajax call. I had the boards loading and then noticed an unfortunate bug that caused multiple windows to be opened when clicking the Pinterest button. Not on the first page load, but each time ajax loaded a new set of embedded boards and I called pinIt_main.js to activate the boards, it creates a new log file. The number of windows opened when a Pinterest button is clicked is equal to the number of log files.

I found this undocumented function for building the boards after the page loads. Unfortunately, when I use pinit.js the embedded boards don't load at all. 

Here is a URL where you can see it in action: http://www.siegemedia.com/clients/wpd/colors/wedding-colors/summer.htm

To replicate, load the URL and choose "black" to see an example of loading the second set of boards with pinit.js. Choose any other color to see an example of the bug that causes multiple windows to open.

**Comment by velles** [comment]
@kentbrew adding to the previous comments. 
This functionality was extremely hard to find. 
Please, please document it in the readme. 
It was very hard to get the preview working on React project without re-building the links.

**Comment by xujy** [comment]
I just came across this thread and implemented the suggestions. It works great, except it seems that `doBuild` is giving me an error I can't recognize, and my widgets start to duplicate and render multiple times randomly. Anybody else come across any issues like this?

![image](https://user-images.githubusercontent.com/12678778/52894985-4fbf7380-3181-11e9-9acb-3f86b6fcee78.png)

Got this error I'm having trouble debugging
