### ISSUE TITLE
log.pinterest.com always being loaded

### ISSUE THREAD

**Issue by mm-tom** [pinterest/widgets#18]
Hi there,

I have a pin this widget loaded on to a photo page that is viewed in a modal window, accessed from a photo gallery.
When the modal window is loaded, an ajax request fetches the html and places it inside the modal window, this is repeated when the user goes to the next or previous photo. The html contains a pin this button. 

However, every single time the html is rendered to the page, the pinterest button injects a script in to the bottom of the DOM, to log.pinterest.com.
If a user on the site continues to browse photos without navigating away from the physical page, then the browser clogs up with these script tags and eventually the browser will crash.
I've tried different methods of getting the script working but not without this issue. Sometimes the script tags seem to get removed after being added, but not always.

Is there a way for me to avoid this? 
Twitter and Facebook widgets have been a lot easier to configure in this scenario.

Ideally of course, this script would not be injected so often, or at least it could ensure there are no existing instances of the script on the page before it injects another one.

**Comment by backpackingseries** [comment]
Hello,

It took me a while to research and get here. I have a problem with a call to log.pinterest.com slowing down my homepage (https://www.backpackingseries.com). I am not sure what this 0 byte resource does (tracking everything?) and wonder if there's a way to get rid of this.

I enqueue the following script to generate Pinterest button:

```
(function(d){
  var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
  p.type = 'text/javascript';
  p.setAttribute('data-pin-hover', true);
  p.async = true;
  p.src = '//assets.pinterest.com/js/pinit.js';
  f.parentNode.insertBefore(p, f);
}(document));
```

Can someone here please help fix this?

Kind regards
