### ISSUE TITLE
Call to log.pinterest.com is very slow / timing out

### ISSUE THREAD

**Issue by AlistairB** [pinterest/widgets#27]
Can take up to ~3 minutes. The call originates from http://assets.pinterest.com/js/pinit.js 

Hitting it from Melbourne, Australia.

Can see this on http://www.boatsales.com.au/boats-for-sale/boatdetails.aspx?R=12752685&Silo=Stock&Vertical=Boat&gts=12752685&Ridx=0&gtssaleid=2635896&eapi=2

**Comment by susanwinters214** [comment]
asset.pinterest call Still running slow - see here: http://www.overheaddoor.com
