### ISSUE TITLE
Check if the script has finished?

### ISSUE THREAD

**Issue by nickyoung87** [pinterest/widgets#28]
Is there currently some kind of event or object I can check to see if the pinit_main.js has finished running? I am writing some jQuery to work with this, but I need to somehow check if the pinit_main.js has finished running all of it's code before I can execute my own.

Thanks

**Comment by kentbrew** [comment]
Please try not to render widgets in hidden tabs; it's terribly wasteful. You could potentially use dynamic rebuilds to make these as your divisions are revealed; poke around in issues and you'll find a fairly long discussion.
