### ISSUE TITLE
Create an valid HTML5 way of excluding images from the pintrest pin it widget

### ISSUE THREAD

**Issue by skeller80** [pinterest/widgets#29]
Currently the only method to exclude images from the pinterest pin it widget is to include the nopin="nopin" attribute which breaks validation in HTML5. Would be nice if we could exclude images with something like data-nopin="nopin".

Thanks,
Scott

**Comment by kentbrew** [comment]
Try this:

`data-pin-nopin="true"`

**Comment by skeller80** [comment]
Works great!

Thanks.
