### ISSUE TITLE
Displaying zero count in "beside" mode

### ISSUE THREAD

**Issue by pderksen** [pinterest/widgets#3]
First off thanks for open sourcing this project. I've been meaning to understand the minified code in pinit.js since I started developing a "Pin It" button WordPress plugin in late 2011.

One request many of my WordPress plugin users ask for is the option to always show the count, even if it's zero and in "beside" mode. I believe it doesn't do this currently. People mainly want it since other social sharing buttons by default show the zero count.

Is this intentional? If so is there a reason? If not, could we have the "zero count visible" option added? Or at least be able to change with a data attribute if not in the widget builder.

Thanks!
Phil

**Comment by pwz3n0** [comment]
!<Ok>,pinit. js behavior
