### ISSUE TITLE
pinning vimeo video via bookmarklet pins thumbnail instead of video

### ISSUE THREAD

**Issue by grischka** [pinterest/widgets#31]
When embedding a vimeo video into a page the video thumbnail is pinned and not the actual url of the video.

Embed Code Example:
``<iframe src="//player.vimeo.com/video/92369879?title=0&byline=0&portrait=0&badge=0&color=ffffff" width="775" height="436" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>``

The bookmarklet (pinmarklet.js) generates this:

``http://www.pinterest.com/pin/create/bookmarklet/?media=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F472081228_1280.jpg&url=[NOT-VIMEO-URL]&description=Birds.%20A%20lighthearted%20essay%20on%20contextualized%20characters.%0AReconstruction%20follows%20deconstruction.%0A%0AConcept%2C%20Art%20Direction%2C%20Design%2C%20Animation%2C...&is_video=true``
(url parameter is the page url and not the url of the video)

It works fine with youtube videos though.

**Comment by kentbrew** [comment]
Fixed, sorry to leave the issue alive for so long.
