### ISSUE TITLE
Fix pin count bubble for "any image" pin it button type

### ISSUE THREAD

**Issue by pderksen** [pinterest/widgets#34]
Thought it might be better to open a new issue for this since the original is pretty old.

Referencing issue #5 ...

I can't seem to get the pin count bubble working with "any image" (buttonBookmark) buttons again. Can this be fixed?

New demo page at https://dl.dropboxusercontent.com/u/7727/pinterest/testing/test-bookmark-count-bubble-2014-05-07.html

Thanks!

**Comment by ghorvat** [comment]
Hey guys is there any progress on this there is still no option in the widget for the count bubble and adding it separately does not work.

Thanks!

Cheers!
