### ISSUE TITLE
Oembed richpins question

### ISSUE THREAD

**Issue by avra911** [pinterest/widgets#36]
Hi everybody,

I followed the developer rules to add rich pins into the website for product.
The validator shows me correctly the item: the image, title, link and price. I am using oembed method (see: https://developers.pinterest.com/rich_pins/validator/?link=http%3A%2F%2Fwww.lofty.com%2Frich-pins%2Foembed%3Furl%3Dfine-art%252Fdale-chihuly-american-b-1941.html ).

However when I pin it from website product page, in my pinterest list, i do not see the price and the link points to the oembed url instead of the url from the json of the oembed url. I also found that some other items shows correct., but this is very randomly, i did not found any pattern.

I would like to see a script example for the pin it button for the oembed method. i personally think there is my problem, or do the items need to be approved somehow!?

Thanks in advanced,
Razvan

**Comment by kentbrew** [comment]
This is not your problem; Rich Pins have not been enabled in widgets. It's on our list of hot requests, however.
