### ISSUE TITLE
Custom button for 'buttonBookmark'

### ISSUE THREAD

**Issue by PieterxJan** [pinterest/widgets#40]
Hi,

Every time when I try to use a Pinterest widget with `data-pin-do=buttonBookmark`, it changes my custom-made button I want to use for this feature. Is there any setting I can use so that pinit.js doesn't override my custom-made button?

**Comment by kentbrew** [comment]
Sorry, we aren't supporting custom buttons at this time. Heard and understood for future enhancements, thanks!
