### ISSUE TITLE
Image size bug with data-pin-media

### ISSUE THREAD

**Issue by plasticmind** [pinterest/widgets#42]
After quite a bit of testing, I've discovered that both the data-pin-media and data-pin-id attributes cause some kind of filtering on the Pinterest image select screen.

If you click the Pin It bookmarklet, you should get all of the images on the page that fit Pinterest's size profile (height, width, aspect ratio), like this:

![2014-12-11 at 6 52 pm](https://cloud.githubusercontent.com/assets/43208/5404631/ec89bbfa-8166-11e4-8eb7-046ad52be8d7.png)

However, if data-pin-media or data-pin-id is set, the size of those images impact the size of the images that get displayed on the Pinterest image select screen, like this (using data-pin-media):

![2014-12-11 at 6 54 pm](https://cloud.githubusercontent.com/assets/43208/5404654/22a8ad5e-8167-11e4-835d-22953c0715d9.png)

Or like this (using data-pin-id):

![2014-12-11 at 6 55 pm](https://cloud.githubusercontent.com/assets/43208/5404666/44d0fe54-8167-11e4-98ca-4034aedc8700.png)

Full demonstration and documentation of the bug here: http://www.simplyrecipes.com/labs/pinterest/data-pin-id/test-1.html?v=5

**Comment by kentbrew** [comment]
Some images are pushed down below the threshold when an especially good image shows up on top, yes. This works really well when we are looking at a big blog index that might have ads all over it.

When you give us a data-pin-id we're going to repin whatever image we already have. Dimensions no longer enter into it.

**Comment by plasticmind** [comment]
Thanks for the feedback, Kent!
