### ISSUE TITLE
HTTPS image not pinnable from non-https domains 

### ISSUE THREAD

**Issue by okor** [pinterest/widgets#43]
In the documentation for the Pinit button (https://developers.pinterest.com/pin_it/) there is a subtle indication that protocols must match (page URL and asset URL). 

> If you click your Pin It button and the bookmarklet pops up (showing all the images on your page in a grid) instead of the form, it's because we didn't receive both URLs. It could also happen if one or both of the URLs didn't start with http or https.

I'm sure there was reason for this but it seems unnecessary and breaks things for a number of sites (including many from Vox Media like Eater.com). Our CDN's can serve up the same asset using either protocol but I'll have to fork and hack the button to fix the pinterest button for our verticals as we started serving all of our assets with HTTPS recently.

I recommend changing this restriction to allow HTTPS images with non-HTTPS share domains.

**Comment by kentbrew** [comment]
Sorry, I'm not following. May I please have an URL to test?
