### ISSUE TITLE
Pin It not appearing in The Old Reader and causing display bug

### ISSUE THREAD

**Issue by eslachance** [pinterest/widgets#44]
Browser: Chrome 39.0.2171.95 m
Reproducable: Yes

Description: When the Printerest Extension is activated in Google Chrome, any image within an RSS feed will cause a visual glitch when hovered: the scrollbar appears on the right of the browser, shifting the contents towards the left.

Cause: It took a bit of sleuthing to realize that the cause was the span element added by Pinterest at the end of the page before the closing body tag. When the image is hovered, the CSS for the span (which I only knew was the Pin It button because I decoded the base64 image!) changes from display:none to display:block , but nothing else changes. The Pin It image does not appear on top of the hovered image. Since the button appears but is not moved, that is what causes the scrollbar to appear. 

Note: I understand that this is an odd cross-service issue, I've also reported this to the The Old Reader staff which suggested I also report it here. Speaking of which, I appologize if this is not the right location to report bugs in the pinterest extension, but to be honest there doesn't seem to be any other way to reach you guys other than facebook, twitter, google+... this seemed like a more relevant location.

**Comment by kentbrew** [comment]
Sorry, I'd have to crack into The Old Reader's styles to figure this out and there just aren't enough hours in the day. I'll guess that something's going on with image positioning or margins that is obscuring the Pin It button. The Pin It button should not bump the scrollbars around, since it's positioned absolutely.
