### ISSUE TITLE
Moving Position

### ISSUE THREAD

**Issue by CologneUserOne** [pinterest/widgets#45]
Hi,
I'd like to move my pinterest hover buttons 200px down and 400px to the right. The height difference would be to make up for padding in the image, and the horizontal change is because it would look a lot better, because these images are silhouettes with transparent backgrounds and the buttons look a little lost on the left.

I haven't been able to figure out what exactly to change in the .js file. Do you have a link to any code samples I could dig through or can you direct me to the right section (more what exactly to change in the section)? Here is the page I am trying to adjust:
kunden.pooliestudios.com/vitramini

Adding some padding in the CSS style put the button in exactly the right spot, along with about 400 other buttons filling up the distance in between the new and original button locations! :) But that's actually the closest I've gotten.

**Comment by kentbrew** [comment]
Sorry, we're not yet adding custom styles for hoverbuttons. It's a popular request, however, and I will add yours to the stack.
