### ISSUE TITLE
page's og:description text used for description when data-pin-description attribute present

### ISSUE THREAD

**Issue by ghodgson** [pinterest/widgets#48]
Hi Ken,

After your response to my previous issue (#46), I experimented using the data-pin-description attribute to set a pin's description text explicitly.  However I am still encountering instances where that attribute's value is ignored and the page's og:description meta tag is used instead.

I've set up a second test page with two images on it: http://thethriftyginger.com/pinterest-debug-page-2/

When I click the "Pin It" button in the Firefox toolbar and select the black image that reads "One", the pre-filled description displays the value from the image's data-pin-description attribute ("Image One - Alt Text"). All is good here!

When I click the "Pin It" button and select the black image that reads "Two", the pre-filled description displays the page's og:description meta value ("Visit the post for more") instead of the image's data-pin-description attribute ("Image Two - Alt Text").

Do you have any idea why the second image's data-pin-description value is being ignored? Is it supported behavior to have multiple "data-pin-description"s on the same page like this?

Thanks,
George

**Comment by kentbrew** [comment]
This is working for me, George. Please reopen if it's still broken?
