### ISSUE TITLE
Programmatic control of the bookmarklet

### ISSUE THREAD

**Issue by Tvrqvoise** [pinterest/widgets#49]
Is there a way to specify which images the bookmarklet should and shouldn't load?  data-pin-* attributes seem to provide some of this functionality, but ideally I'd like to display information about products which aren't on the current page.  Is there a way to achieve this?  Ideally from JavaScript, as opposed to setting a bunch of data in the DOM?

**Comment by kentbrew** [comment]
Sorry, we are looking at the DOM only, not JavaScript.
