### ISSUE TITLE
Takeover of links to pinterest.com

### ISSUE THREAD

**Issue by sjelfull** [pinterest/widgets#50]
We're including the widget script, because we need the Pinterest button in a custom modal window.

However, the script is taking over a share link that is not supposed to be a Pinterest button.

See example here: https://brathwait.com/products/the-minimalist-automatic-wrist-watch-mesh-strap (the share links in the top of the product page).

**Comment by kentbrew** [comment]
Many legacy buttons don't include the appropriate data-pin-do attribute so we are pretty aggressive about taking over links to the pin/create form. To work around, please include a null data-pin-do attribute, like this: 

    data-pin-do="none"
