### ISSUE TITLE
Cannot read property 'bg' of undefined

### ISSUE THREAD

**Issue by lukert33** [pinterest/widgets#51]
Hi there,

This Friday we deployed a pinit widget on our site, and over the weekend had a tremendous amount of user engagement with it. Some time yesterday, however, the widget stopped calling in the grid of pinlets. We haven't changed any of the javascript on the production page in question. 

The Exception reported in the browser console originates in grid.html, a file that I do not believe I have access to. Here's the error:
```
Uncaught TypeError: Cannot read property 'bg' of undefined
(anonymous function)	@	grid.html?1432045852960:579 
```
Line 579 of grid.html is `str = $.v.data.msg[$.a.struc[i]];`

I'm using a simple widget for the images on the whole page: 
```
<a href="//www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark"  data-pin-shape="round" data-pin-height="32" data-pin-error="squawk"></a>
```

And calling `pinit.js` at the bottom of the page:
```
<script type="text/javascript">
  (function(d){
    var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
    p.type = 'text/javascript';
    p.async = true;
    p.src = '//assets.pinterest.com/js/pinit.js';
    f.parentNode.insertBefore(p, f);
  }(document));

  var squawk = function (str) {
    console.log('Squawk! Pinterest API error: ' + str);
  };
</script>
```

I'd greatly appreciate your help on this, as we're looking to roll out pinterest across our site (atlasobscura.com).

**Comment by lukert33** [comment]
Hi there,

The pinterest widget on the branch we'd had deployed is now working again, with no changes to our code. This seems to indicate that something changed with `grid.html`. Do you have any indicators of the stability of the remote html called by pinit_main.js?

**Comment by kentbrew** [comment]
We had a transient error on grid.html; this should be fixed now. Sorry for the trouble!
