### ISSUE TITLE
Does not render if parent element is set to "display:none"

### ISSUE THREAD

**Issue by allout58** [pinterest/widgets#52]
If the original widget tag is inside an element set to `display:none`, the link will not be transformed into the widget.

**Comment by kentbrew** [comment]
Yes, this is as intended. We don't need to be rendering invisible widgets.

**Comment by allout58** [comment]
Would it be possible to have an option to force the render?
I am using Bootstrap's tabs (http://getbootstrap.com/javascript/#tabs) for all the different social media widgets (Twitter, Facebook, Pinterest, etc). If the tab is not currently selected, it is given `display:none` then given `display:block` when selected. If this widget is not in the first tab to be rendered, it is never rendered.
