### ISSUE TITLE
JSONP call to /pins always returns insecure images

### ISSUE THREAD

**Issue by johnpash** [pinterest/widgets#54]
JSONP call to /pins always returns insecure images

I had assumed that if pinit.js was included securely, that all resources would also be secure. The widget resources are however, the pin images are not, causing mixed content warnings.

ex: https://widgets.pinterest.com/v3/pidgets/users/kingandmcgaw/pins/

data.pins.pinner.image_small_url
data.pins.board.image_thumbnail_url
data.pins.images...

**Comment by kentbrew** [comment]
Fixed; sorry this took so long.
