### ISSUE TITLE
Provide an attribute for the "extended" social media format

### ISSUE THREAD

**Issue by keul** [pinterest/widgets#55]
All other major social media provides a way to display the media buttons with a big hit counter:

![schermata 2015-06-19 a 12 52 46](https://cloud.githubusercontent.com/assets/284924/8252079/5c41bc80-1682-11e5-9169-38d8b3d1ad4e.png)

This seems not easily possible with Pinterest pin it button until you provide custom CSS, while other socials simply gives you a way to get this by providing custom HTML 5 attributes.

**Comment by kentbrew** [comment]
You may be looking for `data-pin-count="above"` or `data-pin-count="beside"`.
