### ISSUE TITLE
pinit_main.js not compressed

### ISSUE THREAD

**Issue by michaelcunningham19** [pinterest/widgets#56]
Running Google PageSpeed Insights on a website that has the Pin It button on it produces this message:
<img width="838" alt="screen shot 2015-07-24 at 3 39 41 pm" src="https://cloud.githubusercontent.com/assets/10078342/8882019/54a7d690-321a-11e5-90e1-8139168d0187.png">

Production code like this should be sent with either gzip or deflate to improve performance

**Comment by derekprior** [comment]
I was surprised to see this report as well. Could you please configure your servers to serve this asset gzipped?

**Comment by eat-sleep-code** [comment]
01/02/2016 - This is still an issue according to wepagetest.org

**Comment by YaegerDesign** [comment]
Will the script and CSS be compressed any time soon? It is quite strange that Pinterest would rather serve uncompressed  resources and use 74% more bandwidth on their CDN.

**Comment by kentbrew** [comment]
The compressed version should come down from our CDN when called with a script tag include. Are you saying you want a copy of that here as well?

**Comment by michaelcunningham19** [comment]
@kentbrew 

No, look at the original screenshot, the js file is not being served with GZIP on your CDN

**Comment by YaegerDesign** [comment]
It appears that the script has now been updated with compression. Thanks! Now, how about setting an expiry date or a maximum age in the HTTP headers... :)
