### ISSUE TITLE
Is it possible to disable zero count?

### ISSUE THREAD

**Issue by terriann** [pinterest/widgets#57]
This is somewhat related to #3  and #30 but is there any way to force the 0 bubble to not display when the count is above?  I know that suppressing the 0 count is default behavior when the count is to the right but I'd like to make a configuration in my plugin that allows users to disable it when it's above as well.

I tried `data-pin-zero="false"` but the pinit.js changes that to `data-pin-zero="true"`

Thanks!

**Comment by pwz3n0** [comment]
!<Ok>pinit. js behavior

**Comment by terriann** [comment]
Yes @pwz3n0 I understand it's not native behavior. That's why I'm asking this question. Thanks for the response.

**Comment by kentbrew** [comment]
Closing for the rewrite.
