### ISSUE TITLE
Facebook and Twitter widgets have random 'replacement' characters

### ISSUE THREAD

**Issue by McManCSU** [pinterest/widgets#59]
After poking around, I have noticed some strangeness in the URLs that are behind the facebook and twitter widgets for Pinterest users. Some examples:

* [ ] **facebook**
  - https://www.pinterest.com/vivibe --> `https://www.facebook.com/profile.php?id=%EF%BF%BD030797041`
* [ ] **twitter**: 
  - https://www.pinterest.com/jenrwaugh/ --> `http://twitter.com/http://twitter.com/JenRWaugh`

For the facebook case - from what I understand, the `%EF%BF%BD`  (url decoded `&#65533`) is the browser issuing a replacement character for some unknown character. I have noticed the character in seemingly random positions within the url (sometimes in the ID, sometimes in `facebook.com` - i.e. `https://www.f�cebook.com/profile.php?id=xxxxxx`)

Twitter largely just seems to be duplicated `twitter.com`, no encoding issue that I have noticed

I'm sure you are aware of this, but I wanted to point it out and see if there is an ETA on when it may be fixed.

Thanks

**Comment by kentbrew** [comment]
I'll forward this to the proper authorities, thanks! It's not fixable with our third-party widget code, which does not actually run on pinterest.com.

**Comment by McManCSU** [comment]
Figured as much, thanks for passing along though
