### ISSUE TITLE
Stop pinit.js hijacking all links relating to pinterest.

### ISSUE THREAD

**Issue by mikedidthis** [pinterest/widgets#6]
Is there a way to do either of the following:

Specify the elements that should be turned into a board, pin, widget, etc.

Or:

Tell pinit.js to skip over a specific link containing, `/pinterest.com/pin/create/button/?`, using a class or data-attribute.

I currently use the board widget, but I also have sharing links for pinterest, that I don't want turning into pin buttons.

Many Thanks

**Comment by w33zy** [comment]
Its 2015 and yet this still an ongoing issue. Jesus Christ!!!

**Comment by matthewmcvickar** [comment]
@kentbrew Can you please add this to the documentation at: https://developers.pinterest.com/on_hover_pin_it_buttons/

**Comment by matthewmcvickar** [comment]
The `data-pin-do="skipLink"` attribute appears to have stopped working. Adding the `data-pin-custom="true"` attribute to the link appears to have achieved the same result. https://developers.pinterest.com/docs/widgets/pin-it/#custom

**Comment by jaschaio** [comment]
@kentbrew thanks a lot for documentating this!

I tried it with `data-pin-do="skipLink"` and as @matthewmcvickar said, it's not working. Anyway `data-pin-custom="true"` still does the trick

**Comment by itsbrianburton** [comment]
I was experiencing a problem with the pinit_main.js script overwriting my pinterest share link.  None of the above solutions seem to work anymore.

After reviewing the pinit_main.js source it appears the current solution is to add the following attribute to your `<a>` tag:

`data-pin-do="none"`

**Comment by grantalltodavid** [comment]
thanks @itsbrianburton, you're a lifesaver!

**Comment by kraftner** [comment]
Thanks @itsbrianburton ! :heart: 

For those curious, the relevant lines are those:

https://github.com/pinterest/widgets/blob/a0ad83c665438b902e512ee7422c9644561abcd2/pinit_main.js#L1437-L1441

and

https://github.com/pinterest/widgets/blob/a0ad83c665438b902e512ee7422c9644561abcd2/pinit_main.js#L2232-L2236

As you can see above those options all cause the same result:

```
data-pin-do="ignore"
data-pin-do="none"
data-pin-do="nothing"
```
I'll open another issue about documenting this issue to prevent others wasting hours of their time as well. :roll_eyes:
