### ISSUE TITLE
Google webmaster console flags http://assets.pinterest.com as a Blocked Resource

### ISSUE THREAD

**Issue by nicopujol** [pinterest/widgets#69]
We are seeing a new flag in google's webmaster console for a Blocked Resource that refers to the Pinterest assets. It seems Pinterest's robotx.txt file was accessible to Googlebots until June 28 2016 and started blocking it.

1	http://assets.pinterest.com/js/pinit.js
2	http://assets.pinterest.com/images/pidgets/pin_it_button.png	

From Google:
The page may not render properly due to resources blocked by http://assets.pinterest.com/robots.txt
Update the robots.txt rule to unblock the resource
1
See how Google views your page
Click “Fetch and Render” in the Fetch-as-Google feature to view the page as Google renders it, and compare it to how a browser displays the page. This will help you isolate the impact of the missing resource.
Fetch as Google
2
Verify ownership of the blocked resource host
You must be a verified owner of the site hosting the blocked resources in order to use the robots.txt Tester on that site. If you are not a site owner, contact the owner to perform the next steps.
Verify host
3
Update the blocking robots.txt file
Use the robots.txt Tester on the blocked site to help unblock the resource.
robots.txt tester

**Comment by rhondamorin** [comment]
So what is being done about this? I emailed them and they replied with a canned response: 

-------
Hi Rhonda,
We block links if we think they might be spammy or unsafe. To make sure a link doesn't get blocked:
- Check that the link goes directly to the website, not through a URL shortener (like bit.ly) or redirector
- Pin with our official Pin It button http://about.pinterest.com/goodies/
In some cases, we block a website completely. If you think we made a mistake, just write back with: 
- A link to your website or blog
- A link to a pin that's showing you the block error
Thanks,
The Pinterest Team
-------

Any ideas?

**Comment by kentbrew** [comment]
On it, sorry for late response.

**Comment by kentbrew** [comment]
Should be fixed now. Again, sorry for the dead air!

**Comment by ColinRJones** [comment]
I'm actually experiencing the same thing on our site. It's showing blocked resources in WMT that look like: 

https://api.pinterest.com/v3/pidgets/users/[NAME REMOVED]/pins/	

We have over 1000 pages that are apparently affected, but I'm not sure if this is causing an issue or not. 

thoughts?

**Comment by berenerchamion** [comment]
Similar issue with https://widgets.pinterest.com/v1/urls/count.json and the params that follow. Blocked by robots.txt.

**Comment by jpmelnik** [comment]
> Similar issue with https://widgets.pinterest.com/v1/urls/count.json and the params that follow. Blocked by robots.txt.

Same issue..
