### ISSUE TITLE
buttonBookmark results in mixed / incorrect descriptions

### ISSUE THREAD

**Issue by calebergh** [pinterest/widgets#70]
Per my SO question here: http://stackoverflow.com/questions/39575555/pinterest-button-linking-to-wrong-content

This is on a WordPress site.

The images are all correct, but the descriptions are mixed.  Some are correct, some are from a completely different post.

Two versions of the button have been tried, with the same result:

```
<a href="https://www.pinterest.com/pin/create/button/"
    data-pin-do="buttonBookmark"
    data-pin-url="http://www.example.com/blog/photography-website-redesign"
    data-pin-description="Photography Website Redesign"
    data-pin-count="beside">
        <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" />
</a>
```

and 

```
<a href="https://www.pinterest.com/pin/create/button/"
    data-pin-do="buttonBookmark"
    data-pin-count="beside">
        <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" />
</a>
```

If a live URL would be helpful, let me know.  I can provide one.

**Comment by kentbrew** [comment]
If you're using buttonBookmark it's going to ignore your global data-pin-description and data-pin-url directives; that version of the Save button triggers pinmarklet.js, which does a full-page inventory of all images and makes best guesses of what to suggest for URLs and descriptions.
