### ISSUE TITLE
Response is not compressed on https://widgets.pinterest.com/v3/pidgets/users/<user>/pins

### ISSUE THREAD

**Issue by top1r** [pinterest/widgets#71]
While investigating the webpagetest.org recommendations, I've found that the response is not compressed for https://widgets.pinterest.com/v3/pidgets/users/<user>/pins

Here is the compression test:
http://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly93aWRnZXRzLnBpbnRlcmVzdC5jb20vdjMvcGlkZ2V0cy91c2Vycy9wYW9sb3ZpbGxpb24vcGlucy8/c3ViPXd3dyZjYWxsYmFjaz1QSU5fMTQ0NjQ2MTIwNzIwNS5mLmNhbGxiYWNrWzBd

Is it possible to enable compression for that kind of resources?

Headers:
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 0
Content-Type: application/json
Pinterest-Generated-By: coreapp-ngwidgets-prod-0a01ca8a
Pinterest-Version: 9c12a32
Server: nginx
Via: 1.1 varnish-v4
X-Content-Type-Options: nosniff
X-Pinterest-Host: widgets.pinterest.com
Content-Length: 67832
Accept-Ranges: bytes
Date: Wed, 05 Oct 2016 10:18:46 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-fra1222-FRA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1475662725.945498,VS0,VE410

**Comment by kentbrew** [comment]
I'll pass this to the API team, thanks.
