### ISSUE TITLE
Pin Description not populated from data-pin-description, Firefox/Safari

### ISSUE THREAD

**Issue by jknopp** [pinterest/widgets#73]
Hello,
I'm using the //assets.pinterest.com/js/pinit.js widget, and I've found that when pinning, the pre-populated "Description" value is pulling in from the "alt" attribute on the image, and ignoring my data-pin-description attribute.

How can I ensure that the pre-populated description uses the data-pin-description text?

Browsers where this has been reproduced:
Safari - 9.0.3
Firefox - 49.0.2 & 50.0
Chrome and IE are working as expected.

Example <img> tag:
< img src="/product_images/475x300/FreeBP-02.jpg" alt="Freestyle Pump" class="pinterest-image" data-pin-description="Pinterest copy. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend condimentum posuere. Sed condimentum efficitur.">

**Comment by kentbrew** [comment]
You shouldn't see different results by browser. Please check that you're not actually pinning using the browser extension for some cases?
