### ISSUE TITLE
Save widget position on transformed images 

### ISSUE THREAD

**Issue by peteshilling** [pinterest/widgets#74]
I often transform (translate) images on my sites for animations and centering images in containers. The issue I'm having is the save widget position doesn't seem to take the transformation into account, so its location isn't in the top left as it should be. Is this something that can be, or will be, fixed? Thanks

**Comment by kentbrew** [comment]
I'll add this to our to-do list but I'm not terribly hopeful. Too many combinations of browsers and possible transformations make it harder to test.
