### ISSUE TITLE
Confirmation screen is non-responsive

### ISSUE THREAD

**Issue by greg-murray-volusion** [pinterest/widgets#78]
Calling PinUtils.pinOne({...}) from mobile is responsive on the choose board screen, but not on the second, confirmation screen.  Please advise.  Thanks

![pinone-nonresponsive2ndscreen](https://user-images.githubusercontent.com/22917554/29945596-60448740-8e67-11e7-9f23-6530d3199c4e.png)

**Comment by greg-murray-volusion** [comment]
It is also non-responsive on the login/create user form.

![image](https://user-images.githubusercontent.com/22917554/33330074-7ffd0dbc-d423-11e7-9847-4d8ccecd2997.png)

**Comment by kentbrew** [comment]
Fixed by our PWA, released some time ago. Sorry for radio silence; we will do better!
