### ISSUE TITLE
description does not get posted with the Pin

### ISSUE THREAD

**Issue by greg-murray-volusion** [pinterest/widgets#79]
The description doesn't seem to flow through with the Pin when using PinUtils.pinOne({...}).  It shows up in the pop-up URL:

https://www.pinterest.com/pin/create/button/?........&description=Pacific%20Pullover

Noticed in the network traffic from the Choose Board page, it posts to 

https://www.pinterest.com/resource/PinResource/create/

The source_url still has the description query parameter, but the data options has it as empty.

data:{"options":{"description":"","link":"https://....","board_id":"...","method":"button","image_url":"https://....","share_facebook":false,"share_twitter":false},"context":{}}

**Comment by greg-murray-volusion** [comment]
Further testing revealed that if you modify the description below the image, then it does include it with the pin.  It might be coming from line 788 in pinit_main.js

`href = href + '&description=' + encodeURIComponent($.f.getSelection() || c.description || el.title || el.alt || $.d.title);`

**Comment by kentbrew** [comment]
Please re-open if this is still happening.
