### ISSUE TITLE
Pin button position incorrect inside a slider

### ISSUE THREAD

**Issue by jamesckemp** [pinterest/widgets#82]
I'm using slick slider. When the pin buttons are inserted (via pinit.js or the browser extension) they are positioned incorrectly.

This is because they are given an offset based on the positioned parents. Slick contains all slides inside a long, overflowing, div, but the images always end up in the same place on the page once transitioned.

Simplest solution may be a data attribute we can use if we want to ignore a certain element's position?

`<div data-pin-ignore-offset="true"></div>`

Or, if we can add a data attribute directly to the image to define our own offset?

`<img data-pin-offset="0">`

**Comment by kentbrew** [comment]
Right, we have a long-standing battle with CSS transitions and margins not given in pixels. Sorry about this, but for now it's a wontfix.
