### ISSUE TITLE
data-pin-no-hover doesn't work for 'save button' Chrome extension

### ISSUE THREAD

**Issue by timaikens** [pinterest/widgets#85]
**Issue:** `<img>` tags with `data-pin-no-hover="true"` are not supposed to show the save button on hover, but they do.

**Example page:** https://www.seriouseats.com/2018/04/13-spring-salads-to-say-goodbye-to-winter.html

Using Chrome, version 65.0.3325.181, and Pinterest Save Button extension, version 3.0.81.

**Comment by timaikens** [comment]
I should note that `data-pin-nopin="true"` on an `<img>` tag _does_ work to hide the button, but it also makes the image unable to be pinned at all (or at least when clicking the extension icon in the toolbar).

The desired behavior is that the 'pinit' button does not appear on hover but the image is still able to be pinned (using the extension icon, a custom implementation, etc.).

**Comment by kentbrew** [comment]
This seems to be working; sorry for radio silence!
