### ISSUE TITLE
Default Save button does not work in ie11, iframe issue

### ISSUE THREAD

**Issue by skripnike** [pinterest/widgets#86]
**Default Save button does not work in ie11 and below, iframe issue.**
First one of Examples from here https://developers.pinterest.com/docs/widgets/save/
**Issue:** In internet explorer 11 appear blank iframe.

![image](https://user-images.githubusercontent.com/16020549/39621302-f2f26440-4f96-11e8-9597-e1bf63f9ff58.png)

**Comment by justijndepover** [comment]
Any updates on this? It seems that no inline style attributes are assigned to the html elements.

**Comment by justijndepover** [comment]
Don't know if this is the main issue but it seems that `setAttribute` is not working in IE.
[reference](https://stackoverflow.com/questions/2119300/setattribute-is-not-working-for-style-attribute-on-ie)

**Comment by jonkemp** [comment]
This is also not working in Edge for me. It would be nice if they had a list of browsers which are supported.

**Comment by jonkemp** [comment]
Still doesn't work in Edge. I guess I'll create a new issue for that.
