### ISSUE TITLE
"data-pin-url" attribute ignored with browser plugin or bookmark button

### ISSUE THREAD

**Issue by christophthiele** [pinterest/widgets#87]
I have several images and all are tagged with `data-pin-media`, `data-pin-description` and some have `data-pin-url` on them so they link on a section of the page and not the general overview.

An example markup would look like
`<img src="https://example.com/wp-content/uploads/pins/image-small.png" data-pin-description="description" data-pin-media="https:/example.com/wp-content/uploads/pins/image-big.png" data-pin-url="https://example.com/post/some-name/section-1/">`
The tag used to create the site pin button:
`<a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" data-pin-tall="true"></a>`

Now, using the save button on an image directly, all is fine and the correct URL ist used.
It will correctly pin `https://example.com/post/some-name/section-1/`

If I however use the general save button present on the page, I see all the correct images, all with the correct description, but they all point to the same URL, the data-pin-url attribute is completely ignored.
It will pin `https://example.com/post/wherever-the-pin-button-is/`

That makes for some pretty inconsistent behaviour as the URL our users end up on depends on which save button they click.

**Comment by kentbrew** [comment]
May I have an URL to test, please?

**Comment by kentbrew** [comment]
Should be fixed, please test?
