### ISSUE TITLE
control pinterest save button find image result

### ISSUE THREAD

**Issue by cccczzzyyyy** [pinterest/widgets#89]
i want to add 'save button' in my site, and i use:

```
<a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark">
</a>
```

but my page has iframe from youtube, and i don't want to add video thumbnail in to the save button result.()

i tried add `nopin="nopin" `,but it only works in img tag, and i also tried add  `<a data-pin-do="buttonBookmark" data-pin-tall="true" href="https://www.pinterest.com/pin/create/button/" data-pin-media data-pin-media='image.jpg;image2.jpg;image3.jpg;image4.jpg'></a>` ,because i have multiple image in the page,but this turns out `data-pin-media` can only useful for one image case. is there any way to add 'save button' and specify multiple images in the save button find image result or prevent youtube video in the save button find image result .

**Comment by kentbrew** [comment]
Good bug, thanks! Should be fixed in today's release of pinmarklet.js, which does not require you to do anything with pinit.js. 

To avoid showing YouTube or other pinnable iframed media, please add `nopin="nopin"` to your iframe.

**Comment by cccczzzyyyy** [comment]
thank your reply, and it works!!!
i have a suggestion, since 'save it' button can display all the image except the img with 'nopin', 
is it possible to specify mutiple images with url in the 'save' button, like:
` <a data-pin-do="buttonBookmark" data-pin-tall="true" href="https://www.pinterest.com/pin/create/button/" data-pin-media data-pin-media='image.jpg;image2.jpg;image3.jpg;image4.jpg'></a>` .
because i have a lot img in the page ,and i only wanna some of them to be show in the save button,
and add 'nopin' to other image is a little bit more.
