### ISSUE TITLE
Embedding only works for pins with numeric URLs

### ISSUE THREAD

**Issue by ndewhurst** [pinterest/widgets#90]
We are using pinit.js on our site to support embedding pins using empty `<a>` tags as provided by the Pinterest embed generator - e.g.: 
```
<a data-pin-do="embedPin" href="https://www.pinterest.com/pin/130534089185219120/">
```

This works well for pins with a numeric pin ID in their URL - e.g. https://www.pinterest.com/pin/130534089185219120/

...but fails for pins with the longer, token-esque URL format - e.g. https://www.pinterest.com/pin/AQE1L9ZmmclhwO4OhLjN5dJdx9G69bFfNl2fJfHYLc5RRM-l7UUoGbk/

The widget builder also fails to generate any preview for such pins - e.g. https://developers.pinterest.com/tools/widget-builder/?type=pin&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2FAQE1L9ZmmclhwO4OhLjN5dJdx9G69bFfNl2fJfHYLc5RRM-l7UUoGbk%2F&size=medium

A. Why do some pins have the longer URL format to begin with? (Are they inherently different?)
B. Is there anything we can do to allow those pins to be embedded in the same fashion as the pins with numeric pin IDs in their URLs?

**Comment by kentbrew** [comment]
Pins without numeric URLs are promoted pins and should not appear outside Pinterest. To embed, repin and pin the repin.

**Comment by ndewhurst** [comment]
OK. Thanks for clarifying!
